### ISSUE TITLE
Trouble upgrading Docker image from 1.15.11 to 1.16.0

### ISSUE THREAD

**Issue by Auroch** [watson81/docker-gitea-rpi#2]
Hi,
As mentionned in the title, i tried to my Docker container from image 1.15.11 to 1.16.0 and it restart with such errors : 

```
./setup: line 52: environment-to-ini: command not found
Server listening on :: port 22.
Server listening on 0.0.0.0 port 22.
su-exec: /usr/local/bin/gitea: Permission denied
Received signal 15; terminating.
./setup: line 52: environment-to-ini: command not found
su-exec: /usr/local/bin/gitea: Permission denied
./setup: line 52: environment-to-ini: command not found
su-exec: /usr/local/bin/gitea: Permission denied
```
It's the first time since 2 years I have an issue upgrading Gitea with your images on rpi (probably since version 1.6).
Do you know if some ENV values as to be modified since 1.15.11 ?

**Comment by watson81** [comment]
I don't actually use this image anymore, but I keep building it because someone (you!) was using it. Which also meant that I didn't notice when it broke. I only did a basic "did the gitea executable respond with the correct version number" test, which didn't catch problems with startup like this.

I think that there are multiple issues:
1. #https://github.com/go-gitea/gitea/pull/14762 introduced a new way of configuring the gitea environment in docker. Unfortunately, this takes the form of a compiled go executable that is not included in the gitea release. Thus, I'll need to do some significant work to automate building it myself.
2. #https://github.com/go-gitea/gitea/pull/17846 introduced a new startup sequence. I _think_ this will be relatively easy to fix.

**Comment by watson81** [comment]
@Auroch I think I've got it nice and fixed. Could you please try pulling and running patrickthedev/gitea-rpi:1.16.5-dev? Nothing I changed should cause any problems at run time, but please back up your data first just in case.

**Comment by Auroch** [comment]
@watson81 working perfectly. Thanks a lot !
I only use Gitea for a small family server, but I really appreciate this service. Can I offer you some buck somewhere ?
Obviously, I cannot see the difference here, is your code available somewhere else or can you tell me what you've done ?

**Comment by watson81** [comment]
@Auroch I hadn't pushed the new code yet. I wanted to make sure it worked for you first. Now that I know it works for you, I have pushed the code and also rebuilt all the images from 1.16.0-1.16.5 and pushed to Docker hub.

There's no need to tip me any. I'm just glad that someone is finding the images useful. I'm an engineer at heart but got promoted to a role where I don't get to actually write code anymore. So I enjoy doing this sort of thing. Just keep letting me know when something seems to go wrong with it!
